FROM node:20-alpine

WORKDIR /app

COPY src/frontend/package*.json ./src/frontend/
RUN cd src/frontend && npm install --only=production

COPY src/frontend ./src/frontend

EXPOSE 3000

CMD ["cd", "src/frontend", "&&", "npm", "start"]
